name: blog_app
description: Inspire a Million.

publish_to: 'none'

version: 1.0.18+19

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  
  flutter:
    sdk: flutter

  animated_text_kit: ^4.2.1
  cached_network_image: ^3.2.0
  change_app_package_name: ^1.0.0
  cloud_firestore: ^3.1.8
  cupertino_icons: ^1.0.2
  dynamic_color: ^1.4.0
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  firebase_database: ^9.0.12
  flutter_linkify: ^5.0.2
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.1
  google_sign_in: ^5.2.4
  http: ^0.13.4
  intl: ^0.17.0
  material_floating_search_bar: ^0.3.7
  onesignal_flutter: ^3.3.0
  page_route_transition: ^3.1.2
  shared_preferences: ^2.0.13
  timeago: ^3.2.2
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - lib/assets/icons/
    - lib/assets/image/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
