name: blog_app
description: Inspire a Million.

publish_to: "none"

version: 1.0.23+24

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animated_text_kit: ^4.2.1
  cached_network_image: ^3.2.0
  change_app_package_name: ^1.0.0
  cloud_firestore: ^3.1.8

  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  firebase_database: ^9.0.12
  flutter_linkify: ^5.0.2
  flutter_svg: ^1.0.3

  google_sign_in: ^5.2.4
  http: ^0.13.4
  intl: ^0.17.0

  onesignal_flutter: ^3.3.0
  shared_preferences: ^2.0.13
  timeago: ^3.2.2
  url_launcher: ^6.0.20
  html: ^0.15.0
  shimmer: ^2.0.0
  carousel_slider: ^4.1.1
  unicons: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/assets/icons/
    - lib/assets/image/

  fonts:
    # - family: Albert
    #   fonts:
    #     - asset: lib/assets/fonts/AlbertSans-Medium.ttf
    # - asset: fonts/Schyler-Italic.ttf
    #   style: italic

    - family: Product
      fonts:
        - asset: lib\assets\fonts\Product-Sans\ProductSans-Black.ttf
          weight: 900
        - asset: lib\assets\fonts\Product-Sans\ProductSans-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: lib\assets\fonts\Product-Sans\ProductSans-Bold.ttf
          weight: 900
        - asset: lib\assets\fonts\Product-Sans\ProductSans-Italic.ttf
          style: italic
        - asset: lib\assets\fonts\Product-Sans\ProductSans-Light.ttf
          weight: 500
        - asset: lib\assets\fonts\Product-Sans\ProductSans-LightItalic.ttf
          weight: 500
          style: italic
        - asset: lib\assets\fonts\Product-Sans\ProductSans-Medium.ttf
          weight: 700
        - asset: lib\assets\fonts\Product-Sans\ProductSans-MediumItalic.ttf
          weight: 700
          style: italic
        - asset: lib\assets\fonts\Product-Sans\ProductSans-Regular.ttf
          weight: 600
        - asset: lib\assets\fonts\Product-Sans\ProductSans-Thin.ttf
          weight: 400
        - asset: lib\assets\fonts\Product-Sans\ProductSans-ThinItalic.ttf
          weight: 400
          style: italic
